apiVersion: v1
kind: Secret
metadata:
  # If you change the namespace/name, you must also
  # adjust the rbac rules
  name: machine-controller-hetzner
  namespace: kube-system
type: Opaque
data:
  # Must be base64 encoded like this: echo -n '<<token>>'|base64 -w0
  token: << HETZNER_TOKEN_BASE64_ENCODED >>
---
apiVersion: "machine.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: machine1
spec:
  metadata:
    name: node1
  providerConfig:
    sshPublicKeys:
      - "<< YOUR_PUBLIC_KEY >>"
    cloudProvider: "hetzner"
    cloudProviderSpec:
      token:
        valueFrom:
          namespace: kube-system
          name: machine-controller-hetzner
          key: token
      serverType: "cx11"
      datacenter: ""
      location: "fsn1"
    operatingSystem: "ubuntu"
    operatingSystemSpec:
      distUpgradeOnBoot: false
  roles:
  - "Node"
  versions:
    kubelet: "1.9.2"
    containerRuntime:
      name: "cri-o"
