apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: machine-controller-hetzner
  namespace: kube-system
data:
  cloudProvider: aGV0em5lcg==
  # Base64-encoded credentials
  # Generate via echo -n '{"token":"<YOUR TOKEN>","serverType":"cx11","datacenter":"","location":"fsn1"}'|base64 -w0
  cloudProviderSpec: 'eyJ0b2tlbiI6IkFCQyIsInNlcnZlclR5cGUiOiJjeDExIiwiZGF0YWNlbnRlciI6IiIsImxvY2F0aW9uIjoiZnNuMSJ9'
---
apiVersion: "machine.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: machine1
spec:
  metadata:
    name: node1
  providerConfig:
    sshPublicKeys:
      - "<< YOUR_PUBLIC_KEY >>"
    cloudProviderSecretName: "machine-controller-hetzner"
    operatingSystem: "ubuntu"
    operatingSystemSpec:
      distUpgradeOnBoot: false
  roles:
  - "Node"
  versions:
    kubelet: "1.9.2"
    containerRuntime:
      name: "cri-o"
